// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCFKKl8vhBgntuCe7AzBFxZbZEqo8fwwY',
    appId: '1:692723566202:web:a065ab7109edea6517ddc3',
    messagingSenderId: '692723566202',
    projectId: 'sk-detector',
    authDomain: 'sk-detector.firebaseapp.com',
    storageBucket: 'sk-detector.appspot.com',
    measurementId: 'G-9ZKJ20DCSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClvutdCOJIlpjvQbFNXupRyPGIITu_P-o',
    appId: '1:692723566202:android:238ef9428dd1563b17ddc3',
    messagingSenderId: '692723566202',
    projectId: 'sk-detector',
    storageBucket: 'sk-detector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJCudEIq8tBrfv1ZYhazb3eC9rafjYJLc',
    appId: '1:692723566202:ios:f71e2746be9c6d0517ddc3',
    messagingSenderId: '692723566202',
    projectId: 'sk-detector',
    storageBucket: 'sk-detector.appspot.com',
    iosClientId: '692723566202-i49o0dvuf8v2tb3nnt99f78ftrsvbg7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJCudEIq8tBrfv1ZYhazb3eC9rafjYJLc',
    appId: '1:692723566202:ios:f71e2746be9c6d0517ddc3',
    messagingSenderId: '692723566202',
    projectId: 'sk-detector',
    storageBucket: 'sk-detector.appspot.com',
    iosClientId: '692723566202-i49o0dvuf8v2tb3nnt99f78ftrsvbg7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sk',
  );
}
